# Generated by Django 4.2.4 on 2023-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
